#!/usr/bin/env bash
#
# Open Portfolio installer -- takes a fresh Ubuntu VPS with DNS pointed at it
# to a running, federated single-owner portfolio. Idempotent and safe to
# re-run: every step that writes a secret or creates a resource first checks
# whether it already exists and skips if so, so an interrupted run (e.g. a
# preflight failure) can simply be fixed and re-run from the top.
#
# Four phases (spec §5):
#   1. Preflight   -- DNS, ports, and required local tools. Hard-exits with
#                      exact fix-this instructions on any failure.
#   2. Stack up    -- brings up caddy/pds/app, generates SESSION_SECRET and
#                      OAUTH_JWK, creates the owner's PDS account, writes
#                      OWNER_DID, then restarts `app` so it picks up
#                      everything written to .env this run.
#   3. Recovery key -- generates an offline PLC rotation key via `goat` and
#                      registers it as the account's highest-priority key.
#   4. Relay crawl -- asks the public relay to start crawling this PDS.
#
# Usage: ./setup.sh (run from anywhere; it cd's to its own directory).
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

ENV_FILE=".env"

log()  { printf '==> %s\n' "$*"; }
warn() { printf '\n!! %s\n\n' "$*" >&2; }
fail() { printf '\nERROR: %s\n\n' "$*" >&2; exit 1; }

require_cmd() {
  command -v "$1" >/dev/null 2>&1 || fail "$2"
}

# ---- .env helpers -----------------------------------------------------
#
# Values are written single-quoted so a later `source .env` can't be broken
# by JSON/JWK punctuation (braces, colons, quotes) in a generated secret.
# Every value this script generates is our own openssl/node output, never
# untrusted input, so it never contains a literal single quote.

env_set() {
  local key="$1" value="$2" tmp found=0
  tmp="$(mktemp)"
  if [[ -f "$ENV_FILE" ]]; then
    while IFS= read -r line || [[ -n "$line" ]]; do
      if [[ "$line" == "${key}="* ]]; then
        printf "%s='%s'\n" "$key" "$value" >>"$tmp"
        found=1
      else
        printf '%s\n' "$line" >>"$tmp"
      fi
    done <"$ENV_FILE"
  fi
  if [[ "$found" -eq 0 ]]; then
    printf "%s='%s'\n" "$key" "$value" >>"$tmp"
  fi
  mv "$tmp" "$ENV_FILE"
  printf -v "$key" '%s' "$value"
  export "${key?}"
}

ensure_secret() {
  local var="$1"
  shift
  local current="${!var:-}"
  if [[ -n "$current" ]]; then
    log "${var} already set in ${ENV_FILE}; leaving as-is."
    return 0
  fi
  local value
  value="$("$@")"
  env_set "$var" "$value"
  log "Generated ${var}."
}

# ---- secret generators --------------------------------------------------
# The PDS-facing ones (admin password / JWT secret / PLC rotation key) use
# the exact commands the reference PDS's own installer.sh uses, so a value
# generated here is indistinguishable from one generated by the upstream
# installer.

gen_admin_password() { openssl rand -hex 24; }
gen_jwt_secret() { openssl rand --hex 16; }
gen_rotation_key() {
  openssl ecparam --name secp256k1 --genkey --noout --outform DER \
    | tail --bytes=+8 | head --bytes=32 | xxd --plain --cols 32
}
gen_owner_password() { openssl rand -hex 16; }
gen_session_secret() { openssl rand -hex 32; }

# ES256 private JWK, WITH "kid" (required -- @atproto/oauth-client rejects a
# private_key_jwt keyset entry with no kid). Generated *inside* the app
# container with `docker compose run` so it can use `@atproto/jwk-jose`
# (already a production dependency of apps/site -- nothing extra to install
# on the VPS), the same generation pattern Luminance's launch runbook uses
# for its own OAUTH_JWK_1 (`JoseKey.generate(["ES256"], kid)` then
# `JSON.stringify({...privateJwk, alg: "ES256"})`).
gen_oauth_jwk() {
  # shellcheck disable=SC2016  # single-quoted on purpose: this is a Node script, not a bash expansion.
  docker compose run --rm -T --no-deps app node --input-type=module -e '
    import { JoseKey } from "@atproto/jwk-jose";
    import { randomUUID } from "node:crypto";
    const k = await JoseKey.generate(["ES256"], `owner-${randomUUID()}`);
    console.log(JSON.stringify({ ...k.privateJwk, alg: "ES256" }));
  ' | tail -n1
}

# Extracts a flat top-level string field's value out of a small JSON blob
# (the PDS admin API responses this script parses are flat) without
# depending on jq or python3 being present on a bare VPS.
json_str() {
  local json="$1" field="$2"
  grep -o "\"${field}\"[[:space:]]*:[[:space:]]*\"[^\"]*\"" <<<"$json" \
    | head -n1 \
    | sed -E 's/.*:[[:space:]]*"([^"]*)"/\1/'
}

# pds_call PATH JSON_BODY [admin] -- "admin" sends PDS_ADMIN_PASSWORD as
# HTTP basic auth; anything else calls the endpoint unauthenticated (that's
# how createAccount actually works -- it's gated by the invite code, not by
# admin auth).
#
# Neither the body nor the admin password ever appears in argv: `ps`/
# `/proc/*/cmdline` are readable by other local users on a shared host for
# as long as the curl process is alive, and both `-d '<json>'` and
# `-u admin:<password>` put their argument there verbatim. The body goes in
# over curl's actual stdin (`--data-binary @-`); the admin password goes in
# via a throwaway 0600 netrc file (`--netrc-file`), created fresh per call
# and removed immediately after -- never touching argv, never reused.
pds_call() {
  local path="$1" body="$2" auth="${3:-}"
  local -a curl_args=(-s -w '\n%{http_code}' -H 'Content-Type: application/json' --data-binary @-)
  local netrc_file=""
  if [[ "$auth" == "admin" ]]; then
    netrc_file="$(mktemp)"
    chmod 600 "$netrc_file"
    printf 'machine pds.%s login admin password %s\n' "$DOMAIN" "$PDS_ADMIN_PASSWORD" >"$netrc_file"
    curl_args+=(--netrc-file "$netrc_file")
  fi
  local resp status
  resp="$(printf '%s' "$body" | curl "${curl_args[@]}" "https://pds.${DOMAIN}/xrpc/${path}")"
  [[ -n "$netrc_file" ]] && rm -f "$netrc_file"
  status="${resp##*$'\n'}"
  resp="${resp%$'\n'*}"
  if ((status < 200 || status >= 300)); then
    fail "PDS call to ${path} failed (HTTP ${status}): ${resp}"
  fi
  printf '%s' "$resp"
}

# =========================================================================
# Phase 1: preflight
# =========================================================================
phase_preflight() {
  log "Phase 1/4: preflight"

  require_cmd docker \
    "Docker is not installed. Install it (e.g. \`curl -fsSL https://get.docker.com | sh\`), then re-run ./setup.sh."
  docker compose version >/dev/null 2>&1 \
    || fail "The Docker Compose plugin is missing (\`docker compose version\` failed). Install it: https://docs.docker.com/compose/install/linux/, then re-run."
  require_cmd curl "curl is required. Install it: sudo apt-get update && sudo apt-get install -y curl"
  require_cmd dig "dig is required for the DNS check. Install it: sudo apt-get update && sudo apt-get install -y dnsutils"
  require_cmd openssl "openssl is required to generate secrets. Install it: sudo apt-get update && sudo apt-get install -y openssl"

  if [[ -z "${DOMAIN:-}" || "$DOMAIN" == "example.com" ]]; then
    fail "Set DOMAIN in ${SCRIPT_DIR}/${ENV_FILE} to your real apex domain, then re-run."
  fi
  if [[ -z "${OWNER_EMAIL:-}" || "$OWNER_EMAIL" == *"@example.com" ]]; then
    fail "Set OWNER_EMAIL in ${SCRIPT_DIR}/${ENV_FILE} to a real email address you control, then re-run."
  fi

  local public_ip apex_ip pds_ip
  public_ip="$(curl -fsS https://ifconfig.me)"
  apex_ip="$(dig +short "${DOMAIN}" | tail -n1)"
  pds_ip="$(dig +short "pds.${DOMAIN}" | tail -n1)"

  if [[ "$apex_ip" != "$public_ip" || "$pds_ip" != "$public_ip" ]]; then
    fail "$(
      cat <<EOF
DNS isn't pointed at this server yet.

This server's public IP: ${public_ip}
  ${DOMAIN}       currently resolves to: ${apex_ip:-<nothing>}
  pds.${DOMAIN}   currently resolves to: ${pds_ip:-<nothing>}

Create (or fix) these two DNS records at your registrar/DNS host, wait for
propagation, then re-run ./setup.sh:

  Type   Name              Value
  A      ${DOMAIN}         ${public_ip}
  A      pds.${DOMAIN}     ${public_ip}
EOF
    )"
  fi
  log "DNS OK: both ${DOMAIN} and pds.${DOMAIN} resolve to ${public_ip}."

  # Ports 80/443 free -- UNLESS they're already held by *this* compose
  # project's own caddy container from an earlier run. setup.sh dying
  # partway through (network hiccup mid-phase-2, no `goat` yet so phase 3
  # is finished manually later, etc.) and being re-run is a documented,
  # expected path -- caddy is very likely still up and holding both ports
  # at that point, and that is NOT a conflict, it's the correct resume
  # state. Only a listener that ISN'T this project's own caddy is a real
  # problem, so check that first and only fall through to the raw
  # port-in-use probe (which can't distinguish "ours" from "foreign") when
  # our caddy isn't the one running.
  if docker compose ps --status running --services 2>/dev/null | grep -qx "caddy"; then
    log "Ports 80 and 443 are already held by this project's own caddy (running from a prior ./setup.sh run) -- OK."
  else
    local port
    for port in 80 443; do
      if (exec 3<>"/dev/tcp/127.0.0.1/${port}") 2>/dev/null; then
        exec 3>&- 3<&-
        fail "Port ${port} is already in use on this host, but Caddy needs it for HTTP(S)/TLS. Stop whatever is bound to it (e.g. \`sudo systemctl stop nginx apache2\`), then re-run."
      fi
    done
    log "Ports 80 and 443 are free."
  fi
}

# =========================================================================
# Phase 2: stack up, secrets, owner account
# =========================================================================
ensure_owner_account() {
  if [[ -n "${OWNER_DID:-}" ]]; then
    log "OWNER_DID already set (${OWNER_DID}); skipping account creation."
    return 0
  fi
  ensure_secret OWNER_PASSWORD gen_owner_password

  log "Requesting an invite code from the PDS admin API..."
  local invite_json invite_code
  invite_json="$(pds_call com.atproto.server.createInviteCode '{"useCount":1}' admin)"
  invite_code="$(json_str "$invite_json" code)"
  [[ -n "$invite_code" ]] || fail "Could not read an invite code out of the PDS response: ${invite_json}"

  # createAccount can't be called with handle=${DOMAIN} directly: the
  # reference PDS only ever accepts handles ending in one of its configured
  # `serviceHandleDomains` (a value that MUST start with a literal "."; the
  # image's own default, which this compose file relies on rather than
  # overriding, is `.${PDS_HOSTNAME}` = `.pds.${DOMAIN}` -- verified against
  # the actual @atproto/pds config validation, which throws
  # "Invalid handle domain" for anything not dot-prefixed). A bare apex
  # domain can *never* satisfy a dot-prefixed suffix check, so the account
  # has to be created under a random label on that default domain first, and
  # only afterwards migrated to the bare apex via `updateHandle`, which
  # verifies ownership independently by fetching
  # `https://${DOMAIN}/.well-known/atproto-did` (this app already serves
  # that route from env.OWNER_DID, from an earlier task) -- confirmed
  # against a live test PDS: createAccount rejects `${DOMAIN}` outright
  # ("UnsupportedDomain"), and separately rejects a few obvious labels like
  # "owner"/"admin" ("HandleNotAvailable: Reserved handle"), hence the
  # random label below rather than something reserved-word-shaped.
  local bootstrap_label bootstrap_handle
  bootstrap_label="$(openssl rand -hex 4)"
  bootstrap_handle="o${bootstrap_label}.pds.${DOMAIN}"

  log "Creating the owner account (bootstrap handle ${bootstrap_handle})..."
  local create_body create_json did access_jwt
  create_body="$(printf '{"handle":"%s","email":"%s","password":"%s","inviteCode":"%s"}' \
    "$bootstrap_handle" "$OWNER_EMAIL" "$OWNER_PASSWORD" "$invite_code")"
  create_json="$(pds_call com.atproto.server.createAccount "$create_body")"
  did="$(json_str "$create_json" did)"
  access_jwt="$(json_str "$create_json" accessJwt)"
  [[ -n "$did" && -n "$access_jwt" ]] || fail "Could not read a DID/access token out of the PDS response: ${create_json}"
  env_set OWNER_DID "$did"
  log "Owner account created: ${did}"

  log "Restarting app so https://${DOMAIN}/.well-known/atproto-did serves the new OWNER_DID..."
  docker compose up -d app

  log "Waiting for https://${DOMAIN}/.well-known/atproto-did to serve it (needed to verify the custom handle)..."
  local resolved=""
  for _ in $(seq 1 60); do
    resolved="$(curl -fsS "https://${DOMAIN}/.well-known/atproto-did" 2>/dev/null || true)"
    [[ "$resolved" == "$did" ]] && break
    sleep 2
  done
  if [[ "$resolved" != "$did" ]]; then
    warn "$(
      cat <<EOF
https://${DOMAIN}/.well-known/atproto-did never served OWNER_DID -- skipping
the handle migration to ${DOMAIN}. Your ATProto handle stays
${bootstrap_handle} for now (the app itself doesn't care -- it authenticates
by DID, not handle). Check: docker compose logs app caddy

Retry manually later, once that URL serves ${did}, with a fresh accessJwt
(sign in as ${bootstrap_handle} to get one) and:
  curl -sf -H "Authorization: Bearer <accessJwt>" \\
    -H 'Content-Type: application/json' \\
    -d '{"handle":"${DOMAIN}"}' \\
    https://pds.${DOMAIN}/xrpc/com.atproto.identity.updateHandle
EOF
    )"
    return 0
  fi

  log "Updating the handle to the bare domain (${DOMAIN})..."
  local update_body update_resp status
  update_body="$(printf '{"handle":"%s"}' "$DOMAIN")"
  # Body via stdin, not `-d`/argv -- same reasoning as pds_call above.
  update_resp="$(printf '%s' "$update_body" | curl -s -w '\n%{http_code}' -H "Authorization: Bearer ${access_jwt}" -H 'Content-Type: application/json' \
    --data-binary @- "https://pds.${DOMAIN}/xrpc/com.atproto.identity.updateHandle")"
  status="${update_resp##*$'\n'}"
  if ((status < 200 || status >= 300)); then
    warn "Could not update the handle to ${DOMAIN} (HTTP ${status}): ${update_resp%$'\n'*}. Continuing -- your ATProto handle stays ${bootstrap_handle}; the app works the same either way (DID-based auth), and you can retry the update manually later."
  else
    log "Handle updated: your ATProto handle is now ${DOMAIN}."
  fi
}

phase_stack_up() {
  log "Phase 2/4: stack up"

  ensure_secret PDS_ADMIN_PASSWORD gen_admin_password
  ensure_secret PDS_JWT_SECRET gen_jwt_secret
  ensure_secret PDS_ROTATION_KEY gen_rotation_key

  mkdir -p ./backups
  # The app container runs as the non-root `node` user (uid 1000, see
  # apps/site/Dockerfile); a fresh bind-mounted host directory would
  # otherwise be owned by whoever ran this script (often root), which that
  # user can't write nightly backups into. Chown to that exact uid rather
  # than chmod 777 -- world-writable isn't needed, only that one uid needs
  # write access, and every other local user/process on the host shouldn't
  # get it for free.
  if ! chown 1000:1000 ./backups 2>/dev/null; then
    warn "Could not chown ./backups to uid 1000 (not running as root?) -- nightly backups may fail to write. Fix manually: sudo chown 1000:1000 $(pwd)/backups"
  fi
  chmod 755 ./backups

  log "Building and starting caddy, pds, and app..."
  docker compose up -d --build

  log "Waiting for the PDS to become healthy (this can take a minute on first boot -- TLS cert issuance)..."
  local healthy=0
  for _ in $(seq 1 60); do
    if curl -fsS "https://pds.${DOMAIN}/xrpc/_health" >/dev/null 2>&1; then
      healthy=1
      break
    fi
    sleep 2
  done
  [[ "$healthy" -eq 1 ]] || fail "PDS never became healthy at https://pds.${DOMAIN}/xrpc/_health. Check \`docker compose logs pds\` and \`docker compose logs caddy\`."
  log "PDS is healthy."

  ensure_secret SESSION_SECRET gen_session_secret
  ensure_secret OAUTH_JWK gen_oauth_jwk

  ensure_owner_account

  log "Restarting app so it picks up SESSION_SECRET / OAUTH_JWK / OWNER_DID..."
  docker compose up -d app
}

# =========================================================================
# Phase 3: recovery-key ceremony
# =========================================================================
phase_recovery_key() {
  log "Phase 3/4: recovery-key ceremony"

  if ! command -v goat >/dev/null 2>&1; then
    warn "$(
      cat <<'EOF'
`goat` is not installed, so the recovery-key ceremony (phase 3) and the
relay crawl request (phase 4) are being SKIPPED for now. Your site is live
and usable without them, but you should come back and finish this: without
an offline recovery key, this PDS's own on-disk key is the ONLY key that can
ever recover your identity if this server is lost or compromised.

Install goat, then re-run ./setup.sh (phases 1/2 will skip work already
done and it will pick up here):
  - prebuilt binary: https://github.com/bluesky-social/goat/releases
  - or, with a Go toolchain: go install github.com/bluesky-social/goat@latest
EOF
    )"
    GOAT_AVAILABLE=0
    return 0
  fi
  GOAT_AVAILABLE=1

  if [[ -f ./recovery-key-KEEP-OFFLINE.txt ]]; then
    log "./recovery-key-KEEP-OFFLINE.txt already exists; skipping (delete it and re-run to generate another key)."
    return 0
  fi

  log "Logging in to the owner account for goat..."
  # Login by DID, not handle: the handle migration in phase 2 is
  # best-effort (it can warn and skip, e.g. if the well-known verification
  # hadn't propagated yet), but OWNER_DID is always valid regardless of
  # which handle the account currently has.
  goat account login --username "${OWNER_DID}" --password "${OWNER_PASSWORD}" --pds-host "https://pds.${DOMAIN}"

  log "Generating an offline recovery keypair..."
  local key_out secret_key pub_key
  key_out="$(goat key generate)"
  secret_key="$(awk '/Secret Key/{f=1;next} f{print;exit}' <<<"$key_out" | sed -E 's/^[[:space:]]+//')"
  pub_key="$(awk '/Public Key/{f=1;next} f{print;exit}' <<<"$key_out" | sed -E 's/^[[:space:]]+//')"
  [[ -n "$secret_key" && -n "$pub_key" ]] || fail "Could not parse \`goat key generate\` output:
${key_out}"

  {
    printf 'Open Portfolio offline recovery key -- generated %s\n\n' "$(date -u +%Y-%m-%dT%H:%M:%SZ)"
    printf 'Public key (did:key -- safe to share/publish):\n  %s\n\n' "$pub_key"
    printf 'Private key (multibase -- KEEP THIS OFFLINE):\n  %s\n' "$secret_key"
  } >./recovery-key-KEEP-OFFLINE.txt
  chmod 600 ./recovery-key-KEEP-OFFLINE.txt

  log "Registering it as this identity's highest-priority rotation key..."
  goat account plc add-rotation-key --first "$pub_key"

  cat <<EOF

RECOVERY KEY -- READ THIS NOW
==============================
A new offline recovery key was just saved to:
  ${SCRIPT_DIR}/recovery-key-KEEP-OFFLINE.txt

Move it off this server immediately (password manager, printed on paper, a
hardware vault -- anywhere but this VPS), then delete the file from disk.
Anyone holding this key can rewrite your account's identity.

Per the did:plc specification:

  "The PLC server provides a 72hr window during which a higher authority
  rotation key can 'rewrite' history, clobbering any operations (or chain
  of operations) signed by a lower-authority rotation key."

In practice: this key was just added with --first, making it your
identity's HIGHEST-priority rotation key -- higher than the key this PDS
holds for itself. If this server is ever compromised or seized and someone
uses the PDS's own key against you, you have a 72-hour window from the
moment of the first unauthorized PLC operation to sign and submit a
competing operation with THIS offline key and reclaim control. After that
window closes, the PLC directory treats the compromised chain as final.
Lose this key and you lose that safety net for good -- it cannot be
regenerated after the fact.
EOF
}

# =========================================================================
# Phase 4: relay crawl request
# =========================================================================
phase_relay_crawl() {
  log "Phase 4/4: relay crawl request"

  if [[ "${GOAT_AVAILABLE:-0}" -ne 1 ]]; then
    warn "Skipping the relay crawl request -- goat isn't installed (see phase 3's message above). Once it's installed, run: RELAY_HOST=https://bsky.network goat relay host request-crawl \"pds.${DOMAIN}\""
    return 0
  fi

  log "Asking the public relay to crawl pds.${DOMAIN}..."
  RELAY_HOST="https://bsky.network" goat relay host request-crawl "pds.${DOMAIN}"
  log "Relay crawl requested."
}

# =========================================================================
main() {
  if [[ ! -f "$ENV_FILE" ]]; then
    cp .env.example "$ENV_FILE"
    chmod 600 "$ENV_FILE" # holds secrets from the moment it exists -- owner-read-only from the very first write, not just once setup.sh starts populating it.
    fail "Created ${ENV_FILE} from .env.example. Edit it (set DOMAIN and OWNER_EMAIL at minimum), then re-run ./setup.sh."
  fi
  set -a
  # shellcheck source=/dev/null
  source "$ENV_FILE"
  set +a

  phase_preflight
  phase_stack_up
  phase_recovery_key
  phase_relay_crawl

  cat <<EOF

==========================================================================
Done. Open Portfolio should be live at: https://${DOMAIN}

First login:
  1. Visit https://${DOMAIN}/admin/login
  2. Sign in with your handle (normally "${DOMAIN}" itself -- unless a
     message further up said the handle migration was skipped, in which
     case use the bootstrap handle it printed) and the password below
     (also saved in ${SCRIPT_DIR}/${ENV_FILE} as OWNER_PASSWORD -- the app
     itself never reads that value, it's only for this login):
       ${OWNER_PASSWORD:-<see OWNER_PASSWORD in .env>}
  3. You'll be redirected to pds.${DOMAIN}'s own authorization screen to
     approve the sign-in, then back to your admin dashboard.
==========================================================================
EOF
}

main "$@"
