import { Agent } from "@atproto/api";
import {
  NodeOAuthClient,
  type NodeSavedSession,
  type NodeSavedSessionStore,
  type NodeSavedState,
  type NodeSavedStateStore,
} from "@atproto/oauth-client-node";
import { JoseKey } from "@atproto/jwk-jose";
import type Database from "better-sqlite3";
import { getDb } from "./db";
import { env } from "./env";
import type { FetchJson } from "./pds";

/**
 * Build the client metadata document. Derived entirely from `env.PUBLIC_URL`
 * so the `/oauth/client-metadata.json` route and the OAuth client agree
 * byte-for-byte (the ATProto AS fetches `client_id` and validates the
 * returned metadata). `client_id` is, by ATProto convention, the URL of this
 * very document.
 *
 * Confidential `private_key_jwt` client (matching Luminance's
 * `apps/web/lib/oauth.ts`), not a public one: ATProto's authorization
 * servers grant confidential clients much longer-lived sessions than public
 * clients, and this is an admin CMS opened daily -- frequent forced re-auth
 * is a real cost a single-owner install shouldn't have to pay. `env.OAUTH_JWK`
 * is this instance's ES256 signing key (a per-install secret, not shared
 * across deployments, and never checked into the repo), generated by
 * `setup.sh` (Task A11) the same way Luminance's launch runbook
 * (`docs/runbooks/launch-alpha.md`) generates `OAUTH_JWK_1`:
 * `JoseKey.generate(["ES256"], kid)` then serialized as
 * `JSON.stringify({...key.privateJwk, alg: "ES256"})` -- the `kid` is
 * required in the stored JSON, not optional: `@atproto/oauth-client`
 * rejects a `private_key_jwt` keyset whose key has no `kid`.
 *
 * `scope` (Task A13 finding, diverges from Luminance's own `"atproto"`-only
 * value): `@atproto/oauth-scopes`' granular permission model rejects a blob
 * upload or record write from a session carrying only the bare `atproto`
 * scope with `ScopeMissingError` ("Missing required scope") -- `atproto`
 * alone only establishes identity, per that package's own
 * `ScopePermissionsTransition` class. `transition:generic` is that same
 * package's documented backward-compat scope restoring the older
 * full-account-access behavior a single simple scope string used to imply,
 * which is exactly what this CMS's write path (`app/admin/actions.ts`'s
 * `uploadBlob`/`createRecord`/`putRecord`/`deleteRecord` calls, spanning
 * every `social.opencontent.*` collection) needs. Caught only by A13's real
 * browser-driven OAuth E2E test -- every earlier test drives the write path
 * with a plain session-based `agent` (`network.pds.getAgent()`), never a
 * real OAuth-issued, scope-checked session, so this was never exercised
 * before.
 *
 * Two defects found here were shared with Luminance's own
 * `apps/web/lib/oauth.ts`: this same narrow `"atproto"`-only scope, and a
 * second, independent bug in how it constructs its OAuth client -- building
 * a fresh `NodeOAuthClient` on every call, rather than caching one per
 * config the way {@link getOAuthClient} below does, hands out a fresh, empty
 * in-memory DPoP-nonce cache on every request. That was also found by A13's
 * real-browser E2E: the resulting nonce-discovery retry crashes on a
 * non-replayable request body under Next's bundled server code, breaking
 * every post-login PDS write. Both defects were found here and fixed in
 * Luminance 2026-07-28.
 */
function clientMetadata() {
  const base = env.PUBLIC_URL;
  return {
    client_id: `${base}/oauth/client-metadata.json`,
    client_name: "Open Portfolio Admin",
    client_uri: base,
    redirect_uris: [`${base}/oauth/callback`] as [string],
    grant_types: ["authorization_code", "refresh_token"] as ["authorization_code", "refresh_token"],
    response_types: ["code"] as ["code"],
    scope: "atproto transition:generic",
    application_type: "web" as const,
    token_endpoint_auth_method: "private_key_jwt" as const,
    token_endpoint_auth_signing_alg: "ES256",
    dpop_bound_access_tokens: true,
    jwks_uri: `${base}/oauth/jwks.json`,
  };
}

/** Public client-metadata document, for the `/oauth/client-metadata.json` route. */
export function getClientMetadata() {
  return clientMetadata();
}

// ---- SQLite-backed OAuth stores --------------------------------------------
//
// @atproto/oauth-client-node's stateStore/sessionStore are async interfaces
// (so the library can be pointed at any backing store); better-sqlite3 is
// synchronous end-to-end, so every method here just wraps an already-run
// prepared statement in a `Promise`-returning function. `state`/`session`
// are opaque library-owned objects, serialized as JSON text (SQLite has no
// native JSON column type) -- this app never reads or writes their fields
// directly, only round-trips them for the OAuth client. Store shapes
// (`NodeSavedStateStore`/`NodeSavedSessionStore`) are the library's own
// exported types, not hand-rolled ones.

/**
 * `oauth_states` holds one short-lived row per in-flight authorize->callback
 * round trip (PKCE verifier + DPoP key). `INSERT OR REPLACE` keyed on the
 * nonce `key` covers both first-write and any re-write the library performs
 * mid-flow.
 */
export function makeStateStore(db: Database.Database): NodeSavedStateStore {
  const upsert = db.prepare("INSERT OR REPLACE INTO oauth_states (key, state, created_at) VALUES (?, ?, ?)");
  const select = db.prepare("SELECT state FROM oauth_states WHERE key = ?");
  const del = db.prepare("DELETE FROM oauth_states WHERE key = ?");

  return {
    async set(key, state) {
      upsert.run(key, JSON.stringify(state), Date.now());
    },
    async get(key) {
      const row = select.get(key) as { state: string } | undefined;
      return row ? (JSON.parse(row.state) as NodeSavedState) : undefined;
    },
    async del(key) {
      del.run(key);
    },
  };
}

/**
 * `oauth_sessions` holds the durable (refresh-token-bearing) session per
 * authenticated DID. `INSERT OR REPLACE` both creates the row on first sign-in
 * and updates it (including `updated_at`) on every later token refresh.
 */
export function makeSessionStore(db: Database.Database): NodeSavedSessionStore {
  const upsert = db.prepare("INSERT OR REPLACE INTO oauth_sessions (key, session, updated_at) VALUES (?, ?, ?)");
  const select = db.prepare("SELECT session FROM oauth_sessions WHERE key = ?");
  const del = db.prepare("DELETE FROM oauth_sessions WHERE key = ?");

  return {
    async set(key, session) {
      upsert.run(key, JSON.stringify(session), Date.now());
    },
    async get(key) {
      const row = select.get(key) as { session: string } | undefined;
      return row ? (JSON.parse(row.session) as NodeSavedSession) : undefined;
    },
    async del(key) {
      del.run(key);
    },
  };
}

/**
 * Deletes `oauth_states` rows whose `created_at` is older than `olderThanMs`
 * ago. These rows are only ever meant to live for the few seconds/minutes of
 * a single authorize->callback round trip; anything older is an abandoned
 * flow (the visitor never completed sign-in) and safe to garbage-collect.
 * Returns the number of rows deleted. `db` defaults to the process singleton
 * (production call sites); tests inject their own in-memory db.
 */
export function pruneOauthStates(olderThanMs: number, db: Database.Database = getDb()): number {
  const cutoff = Date.now() - olderThanMs;
  const result = db.prepare("DELETE FROM oauth_states WHERE created_at < ?").run(cutoff);
  return result.changes;
}

// Config-keyed cache for getOAuthClient(), populated below. A plain
// module-scope singleton would be simplest given this app's fixed-for-the-
// process-lifetime env vars, but keying on the actual config values instead
// (a) stays correct if that assumption ever changes and (b) -- the reason it
// matters today -- lets tests that vary PUBLIC_URL/OAUTH_JWK/OAUTH_PLC_URL
// across cases (oauth-stores.test.ts) get a fresh client per distinct config
// with no separate test-only reset function needed.
let cachedOAuthClient: { key: string; client: NodeOAuthClient } | undefined;

/**
 * Construct the OAuth client. Built lazily (never at module load) so the app
 * builds with zero env vars -- `env.*` and `OAUTH_JWK` are only read when a
 * real OAuth request comes in. State/session are persisted in SQLite (via
 * the stores above) so the flow survives across the stateless serverless
 * requests of the authorize -> callback round trip.
 *
 * Cached (see {@link cachedOAuthClient}) rather than rebuilt on every call --
 * critically, `@atproto/oauth-client`'s DPoP-nonce cache lives ON the client
 * instance (an in-memory `SimpleStoreMemory`, per its own source), not in our
 * SQLite stores. A fresh `NodeOAuthClient` per call means a fresh, empty
 * nonce cache every time, which forces a nonce-discovery retry on every
 * single authenticated PDS request (never just the first) -- and that retry
 * path was found (Task A13's real-browser E2E, the first test ever to drive
 * a real OAuth+DPoP session end to end) to crash on a non-replayable request
 * body when running inside Next's bundled server code, breaking every
 * post-login PDS write (e.g. publishing a photo right after signing in).
 * Reusing one client for the process's life means the nonce learned during
 * `/oauth/callback`'s own token exchange (same PDS origin, acting as both AS
 * and RS here) is already warm by the time the first authenticated write
 * happens, so the crashing retry path is no longer hit in the common case.
 */
export async function getOAuthClient(): Promise<NodeOAuthClient> {
  const db = getDb();
  // See env.OAUTH_PLC_URL's own doc comment: unset in production (every
  // field below is omitted, library defaults apply), set only by the
  // Playwright harness (Task A13) to redirect identity resolution at a local
  // dev-env network and tolerate its http-only endpoints.
  const devPlcUrl = env.OAUTH_PLC_URL;
  // PDS_URL only actually affects the constructed client when devPlcUrl is
  // set (it becomes the handleResolver base below) -- only fold it into the
  // cache key in that case, so a plain production call site (devPlcUrl
  // unset) never requires PDS_URL just to build an OAuth client.
  const key = JSON.stringify([env.PUBLIC_URL, env.OAUTH_JWK, devPlcUrl, devPlcUrl ? env.PDS_URL : undefined]);
  if (cachedOAuthClient?.key === key) return cachedOAuthClient.client;

  const client = new NodeOAuthClient({
    clientMetadata: clientMetadata(),
    keyset: [await JoseKey.fromImportable(JSON.parse(env.OAUTH_JWK))],
    stateStore: makeStateStore(db),
    sessionStore: makeSessionStore(db),
    ...(devPlcUrl ? { handleResolver: env.PDS_URL, plcDirectoryUrl: devPlcUrl, allowHttp: true } : {}),
  });
  cachedOAuthClient = { key, client };
  return client;
}

/**
 * Public JWKS derived from the signing keyset, for the `/oauth/jwks.json`
 * route. `publicJwk` strips the private `d` component, so only public key
 * material is ever serialized here -- same guarantee as Luminance's
 * `getPublicJwks`.
 */
export async function getPublicJwks() {
  const key = await JoseKey.fromImportable(JSON.parse(env.OAUTH_JWK));
  return { keys: [key.publicJwk] };
}

/**
 * Restores the owner's persisted OAuth session and wraps it in an `Agent`,
 * for server actions that need to write to the owner's own repo.
 * `client.restore(did)` returns an `OAuthSession` exposing a `did` getter and
 * a `fetchHandler` -- exactly the `SessionManager` shape `Agent`'s
 * constructor accepts directly (`new Agent(session)`), same as Luminance's
 * `restoreAgent` in `apps/web/lib/interactions.ts`.
 */
export async function restoreAgent(did: string): Promise<Agent> {
  const client = await getOAuthClient();
  const session = await client.restore(did);
  return new Agent(session);
}

async function defaultFetchJson(url: string): Promise<unknown> {
  const res = await fetch(url);
  if (!res.ok) throw new Error(`describeRepo fetch ${url}: ${res.status}`);
  return res.json();
}

/**
 * Best-effort handle resolution for a signed-in DID, via
 * `com.atproto.repo.describeRepo` against the pinned `env.PDS_URL`. Unlike
 * Luminance's multi-tenant `resolveHandle` (which resolves an arbitrary
 * DID's *own* PDS via its DID document, since Luminance hosts many
 * photographers each on their own PDS), this app is pinned to a single repo
 * -- there is exactly one PDS to ask. This lookup only ever succeeds for
 * `env.OWNER_DID`; a non-owner visitor completing OAuth with their own
 * unrelated handle (anyone can start the login flow -- only `env.OWNER_DID`
 * unlocks admin via `requireOwner()`) will simply get a failed lookup here,
 * which is fine: every call site treats failure as "leave handle unset,"
 * never as fatal.
 */
export async function resolveHandle(
  did: string,
  fetchJson: FetchJson = defaultFetchJson,
): Promise<string | undefined> {
  try {
    const url = `${env.PDS_URL}/xrpc/com.atproto.repo.describeRepo?repo=${encodeURIComponent(did)}`;
    const data = (await fetchJson(url)) as { handle?: string };
    return data.handle;
  } catch {
    return undefined;
  }
}
